/*
 *	Service localication.js file is used to
 *	centeralized all the message which are return
 *	through the api endpoint response.
 **/
var config = require('./../../config');

module.exports = {
	
	"paymentSuccess":"Payment success!",
	"PasswordError": "Invalid password.",
	"missingParamError": "Please check the parameters passed",
	"invalidInputVale": "Please check the parameters passed",
	"emailValidationError": "Please enter a valid email addesss",
	"error":"False",
	"ServerError":"Server error occurred, Please try again",
	"paymentFailed":`Payment failed!\n\nIf you're seeing this by mistake, send an email with your concern to ${config.support_email}.`,
	"NotYourMoveError":"Not your move",
	"invalidRequestParams": "Invalid Request parameters passed",
	"AccountError":"Account not found, Please try again",
	"invalidCredentials":"Please check your credentials & try again",
	"zipValidationError":"Please enter a valid zip code",
	"mobileValidationError":"Please enter a valid mobile number",
	"usernameValidationError":"Please enter a valid username",
	"passwordValidationError":"Password must be 6-12 characters long",
	"passwordLengthValidationError":"Please enter a valid password",
	"emailExistError":"An account already exist with same email address",
	"mobileExistError":"An account already exist with same mobile number",
	"otpGenerateError":"Error sending otp, please check your mobile number",
	"registerSuccess":"SUCCESS",
	"loginSuccess":"SUCCESS",
	"accountDeactivated":"Your account has been deactivated by admin",
	"accountDeleted":"Your account has been deleted by admin",
	"verificationPending":"Please Verify your mobile number to continue",
	"otpValidationError":"Invalid otp entered",
	"accountDeactivatedOtp":"Your account was deactivated due to too many false OTP entered.",
	"falseOtpResent":"Too many false attempts, new otp was sent to your registered mobile number.",
	"otpExpired":"Otp has been expired, Please generate again",
	"countryCodeValidationError":"Please enter a valid country code",
	"paymentTypeValidationError": "Please enter valid Payment type",
	"deviceTypeError":"Invalid device type provided. Allowed ['ios','android','web']",
	"tokenExpired":"Unauthorised! Access denied",
	"rightsFail":"You are not authorised to perform this action",
	"autologinSuccess":"SUCCESS",
	"categoryNotFound":"Invalid category id provided",
	"listCategorySuccess":"SUCCESS",
	"dateValidationError":"Invalid date provided",
	"contactSuccess":"SUCCESS",
	"OtpSent":"Otp sent successfully",
	"mobileAccountDoesNotExistError":"No account found on our system associated with this mobile number",
	"emailAccountDoesNotExistError":"No account found on our system associated with this email address",
	"resetPasswordSuccess":"SUCCESS",
	"emailOrMobilenoMissingError":"Please enter a valid email address or mobile number to continue",
	"securityQuestionValidationError":"Incorrect security question / answer provided",
	"resetPasswordEmailSent":"SUCCESS",
	"resetPasswordSMSSent":"SUCCESS",
	"resetPasswordEmailError":"Error sending reset password email, please try again",
	"listSecurityQuesSuccess":"SUCCESS",
	"setSecurityQuesSuccess":"SUCCESS",
	"incorrectPassword":"Incorrect password entered",
	"changePasswordSuccess":"Password changed successfully",
	"success":"SUCCESS",
	"TransactionsHistory":"SUCCESS",
	"invalidPlanId":"Invalid plan id provided",
	"invalidOldPassError":"Invalid Old Password",
	"invalidNewPassError":"Invalid New Password",
	"invalidConfirmPassError":"Invalid Confirm Password",
	"allFiledError": "All fields are mandatory",
	"notenoughcreditserror":"You don't have enough credits to perform this action",
	"invalidIdError": "Invaild id provided",
	"invalidAmountError": "Invalid amount entered",
	"noApplicationFound": "No job application found for given details",
	"alreadyRespondedJobApplication": "Already responded for this job application",
	"invalidResponseError": "Invalid response provided",
	"notAllowedToReview": "You are not allowed to review on this post",
	"fileUploadError": "Error uploading file",
	"notHiredError": "Only people hired for this job can post review about this",
	"notHiredCandidate": "The candidate is not hired for this job",
	"notHiredAudition": "Only people hired for this job can post audition about this",
	"alreadyPostedAudition": "You already posted audition for this job",
	"alreadyShortlisted": "You are already shortlisted for this job",
	"alreadyApplied": "This user has already applied for this job",
	"linkExpired":"Reset link has been expired",
	"linkInvalid":"Invalid link provided.",
	"userActivate": "User Activated Successfully",
    "userDeActivate": "User De-Activated Successfully",
	"missingParamErrorAdmin":"Please complete all fields to continue",
	"missingParamErrorAdminR":"Please complete all the required fields to continue",
	"recordExistError":"Record with same details already exists",
	"addGalleryError": "Please add at least one image with description in gallery",
	"invalidRating": "Invalid rating provided",
	"boExist": "Box office data already exist for this date, please update from list.",
	"noFilesProvided": "No files provided",
	"noDataFound": "No data found for given details",
	"yearExistError": "Year already exist in this award",
	"yearNotExistError": "Year record does not exist in this award",
	"resetMessageSent": "Reset link sent via message successfully",
	"notAuthorised": "You are not authorised to perform this action",
	"otpSendError": "Error occurred while sending otp",
	"mp3Only": "Only mp3 file is allowed for songs",
	"appLinkSuccess": "App Link Sent!",
	"appLinkError": "Error occurred while sending App Link",
	"oldPasswordMatchError":"Incorrect password entered for old password",
	"accountExistError": "Account does not exist",
	"roleExist": "Role already exist",
	"roleAssignedError": "Can not remove role, as its assigned to a data executive",
	"recordNoAccessError": "Can not delete this role, its permanent!",
	"recordNoAccessUpdateError": "Can not update this role, its permanent!",
	"invalidReferralCodeError": "Invalid Referral Code Provided",
	"newFbAccountError": "Please provide fb user details",
	"profileUpdateError": "Profile updated successfully!",
	"disclaimerUpdate": "updated successfully!",
	"pushSuccess":"Push SUCCESS",
	"success":"SUCCESS",
	"gameActivation":"Play at least 1 Public/Private game to activate free spin",
	"timeActivation":"Spin will be unlocked when the countdown ends.",
	"spinSuccess" : "Free spin is up for grabs, try your luck!",
	"pushError":"Push Error",
	"referralSuccess":"Referral Record!",
	"pushValidationError": "Please provide valid Boolean value.",
	"emailVerificationSuccess": "Your email address has been verified.",
	"emailVerificationSuccessMsg": `Now you can enjoy all features of ${process.env.PROJECT_NAME}. Thank you!`,
	"passwordNotMatchError" : "Password does not match!",
	"webPassSuccess": "Password change successfully!",
	"uniqueUserNameError": "This username has been taken. Please choose another.",
	"usernameValidationError": "Username must be at least 3 characters long and less than 12 characters.",
	"tableSuccess": "Private Room Created Successfully.",
	"insufficientBalanceError": "Sorry, you have insufficient balance to play this game.",
	"insufficientWithdrawlError": "Sorry, you have insufficient balance to place this request.",
	"alreadyPlaying": "You are playing somewhere else.",
	"tableDoesNotExist": "Table Does Not Exist",
	"tableAlreadyFullErr": "Table is already full.",
	"invalidEmail": "Invalid email address entered",
	"referralPushSuccess": "Congratulations! You received referral bonus",
	"withdrawlPushSuccess": "Congratulations! Your withdrawl request processed successfully.",
	"withdrawlPushReject": "Sorry! Your withdrawl request is rejected.",
	"requestSuccess": "Request processed successfully",
	"accountVerifiedError": "Your email id is not verified!",
	"minWithdrawalLimit": "Minimum withdrawal limit is ",
	"invalidRquest": "Invalid request id provided",
	"withdrawalRequestProcessed": "Request processed successfully",
	"addmoneyRequestProcessed": "Request processed successfully",
	"adminAmountPushSuccess": "Your account has been credited",
	"gamePushSuccess": "Congratulations! You have won a game.",
	"resetEmailAlreadySent": "Reset password email link already sent, please follow the link to reset password",
	"notEnoughAmount": "Sorry, there is not enough amount in user's wallet to make this deduction",
	"hackError": "Unauthorized access! This will leads to permanent account deletion.",
	"emailSentSuccess": "Email sent successfully, please check your inbox"
};